M48
; DRILL file {KiCad (6.0.7)} date Sun Jan 15 17:43:20 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-15T17:43:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0248
%
G90
G05
T1
X2.0581Y-3.7559
T2
X1.8219Y-3.7559
X2.0581Y-3.7559
T0
M30
